version: '3'
services:
  job_front:
    build: .
    restart: always
    volumes:
        - /etc/localtime:/etc/localtime:ro
    ports:
        - 127.0.0.1:3000:3000
    networks:
        - docker_Build




networks:
    docker_Build:
      external: true

